#!/bin/bash

# Display header
echo "PID   PPID  USER       STAT  %CPU %MEM   COMMAND"

# Use ps command to display processes with additional information
ps aux --forest | awk '{printf "%-5s %-5s %-10s %-5s %-4s %-4s   %s\n", $2, $3, $1, $8, $3, $4, $11}'

