#!/usr/bin/env bash
#display best school 10 times the hi on the 9th iteration
counter=0
while [ $counter -lt 10 ]
do
    if [ $counter -eq 8 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
